### ISSUE TITLE
Cannot build on OS X 10.9.2, Node v0.10.26, npm 1.4.3, node-gyp v0.10.10

### ISSUE THREAD

**Issue by qubyte** [chrisa/node-dtrace-provider#44]
I get the following error when attempting to install dtrace-provider with `npm install dtrace-provider`:

```bash
npm http GET https://registry.npmjs.org/dtrace-provider
npm http 200 https://registry.npmjs.org/dtrace-provider
npm http GET https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.2.8.tgz
npm http 200 https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.2.8.tgz

> dtrace-provider@0.2.8 install /Users/mark/Documents/domainMiddleware/node_modules/dtrace-provider
> node-gyp rebuild

  ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
gmake[1]: Entering directory '/Users/mark/Documents/domainMiddleware/node_modules/dtrace-provider/libusdt'
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64   -c -o usdt.o usdt.c
In file included from usdt.c:5:0:
usdt_internal.h:5:24: fatal error: sys/dtrace.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'usdt.o' failed
gmake[1]: *** [usdt.o] Error 1
gmake[1]: Leaving directory '/Users/mark/Documents/domainMiddleware/node_modules/dtrace-provider/libusdt'
make: *** [.] Error 2
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mark/Documents/domainMiddleware/node_modules/dtrace-provider
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dtrace-provider@0.2.8 install script.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "dtrace-provider"
npm ERR! cwd /Users/mark/Documents/domainMiddleware
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mark/Documents/domainMiddleware/npm-debug.log
npm ERR! not ok code 0
```

I've tried cleaning the cache etc.

**Comment by barryo** [comment]
+1

**Comment by trentm** [comment]
That's with v0.2.8. Latest is 0.4.0. Can you retry with the latest dtrace-provider?

**Comment by davepacheco** [comment]
Closing this because there are several newer versions and this has been tested on a bunch of configurations.  Please do reopen if you're still seeing this!
